---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly #
    container_name: mealie
    ports:
        - "9925:9000" #
    deploy:
      resources:
        limits:
          memory: 1000M #
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://recipies.katoteros.org
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_FROM_NAME=Mealie
      - SMTP_FROM_EMAIL=contact@katoteros.org
      - SMTP_AUTH_STRATEGY=TLS
      - SMTP_USER=michelfrancisb@gmail.com
      - SMTP_PASSWORD=  #REPLACE WITH SMTP APP PASSWORD
      - THEME_DARK_PRIMARY=#0000ff
    restart: always

volumes:
  mealie-data:
    driver: local